name : Resourcepack Zipper
on:
  push:
    branches:
      - main  # Adjust this branch name if needed
jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.13.3'
        - name: Run Python Build script
          run: python build.py
        - name: Create ZIP file
          run: |
            COMMIT_ID=$(git rev-parse --short HEAD)
            ZIP_NAME="Shulker_Labels_build.${{ github.run_number }}.zip"
            echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV
            zip -r "${ZIP_NAME}" . -x ".git/*" ".github/*" "build.py" "custom_definitions.json" ".gitignore" "block_models.json" "item_models.json"
        - name: Upload ZIP artifact
          uses: actions/upload-artifact@v4
          with:
            name: resource-pack-artifact
            path: "${{ env.ZIP_NAME }}"