name: Build and Create Release

on:
  push:
    tags:
      - 'v*' # This triggers the workflow when you push a tag starting with 'v'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Read changelog file
      id: read-changelog
      run: |
        CHANGELOG=$(cat CHANGELOG.md)
        CHANGELOG="${CHANGELOG//'%0A'/$'\n'}"
        CHANGELOG="${CHANGELOG//'%0D'/$'\r'}"
        CHANGELOG="${CHANGELOG//'%25'/'%'}"
        echo "DECODED_CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.3'
        
    - name: Run Python Build script
      run: python build.py
      
    - name: Create ZIP file
      run: |
        COMMIT_ID=$(git rev-parse --short HEAD)
        ZIP_NAME="Shulker Labels [${{ github.ref_name }}].zip"
        echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV
        zip -r "${ZIP_NAME}" . -x ".git/*" ".github/*" "build.py" "custom_definitions.json" ".gitignore" "block_models.json" "item_models.json" "scan.py"

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: resource-pack-artifact
        path: ${{ env.ZIP_NAME }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ${{ steps.read-changelog.outputs.changelog }}
          Automated release created by GitHub Actions
        draft: false
        prerelease: false
    - name: Upload Release Artifact
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.ZIP_NAME }}
        asset_name: "${{ env.ZIP_NAME }}"
        asset_content_type: application/zip
        
    - name: Upload to Modrinth
      uses: cloudnode-pro/modrinth-publish@v2
      with:
        project: zRG512nH
        version: ${{ github.ref_name }}
        loaders: '["minecraft"]'
        game-versions: '["1.21.5","1.21.6","1.21.7","1.21.8","1.21.9"]'
        files: '${{ env.ZIP_NAME }}'
        token: ${{ secrets.MODRINTH }}
        changelog: ${{ steps.read-changelog.outputs.DECODED_CHANGELOG }}
    - name: "Actions for Discord"
      uses: Ilshidur/action-discord@0.4.0
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: "Shulker Lables"
        DISCORD_AVATAR: https://github.com/ThatCuteOne/shulker-labels/blob/main/pack.png?raw=true
        DISCORD_MENTIONS: >-
          {
            "allowed_mentions": {
              "roles": ["1325604992484376688"]
            }
          }

      with:
        args: "<@&1325604992484376688>\n${{ steps.read-changelog.outputs.DECODED_CHANGELOG }}\nDownload: https://modrinth.com/resourcepack/shulker-labels/version/${{ github.ref_name }}"